apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test  # ArgoCD에서 관리할 애플리케이션 이름
  namespace: argocd  # ArgoCD가 설치된 네임스페이스
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.build-acceptance-test: ""
spec:
  project: default  # ArgoCD 프로젝트 이름 (기본적으로 `default` 프로젝트 사용)
  source:
    repoURL: 'https://github.com/huinno-yoseph/argo-test.git'  # Helm 차트가 있는 Git 리포지토리
    targetRevision: HEAD  # 배포할 Git 브랜치 또는 커밋 (HEAD로 최신 사용)
    path: 'app-test'  # Helm 차트의 경로 (루트 경로일 경우 '.' 사용)
    helm:
      valueFiles:
        - values.yaml  # values.yaml 파일 경로
  destination:
    server: 'https://kubernetes.default.svc'  # 배포할 Kubernetes 클러스터 주소 (기본 인프로미스 환경)
    namespace: default  # nginx가 배포될 네임스페이스
  syncPolicy:
    automated:  # 자동 동기화 설정
      prune: true  # 불필요한 리소스 삭제
      selfHeal: true  # 클러스터 상태와 선언적 상태가 다를 경우 자동 수정