apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-test.fullname" . }}
  labels:
    app: {{ include "app-test.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "app-test.name" . }}